eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: currency-exchange
  jpa:
    show-sql: true
  h2:    console:      enabled: true


