spring:
  application:
    name: zuul-server
  cloud:
   loadbalancer:
     ribbon:
       enabled: false
server:
  port: 8765
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
